# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('data', models.DateField()),
                ('local', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('horario', models.TimeField()),
                ('organizador', models.CharField(max_length=200)),
                ('email_organizador', models.EmailField(max_length=254)),
            ],
        ),
    ]
